### ISSUE TITLE
Error when Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by cjbottaro** [edgurgel/httpoison#415]
Hello.

Here's the error:
```
payload = Jason.encode!(%{opportunity_id: opportunity_id})
resp = HTTPoison.post("http://ia-web/api/v0/swccd/build_automatch_query", payload)
{:ok, %{status_code: 200, body: body}} = resp

** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: {:more, {:hparser, :response, 4096, 10, 0, :on_trailers, "", {1, 1}, "", [], :undefined, "chunked", "", "application/json; charset=utf-8", "", :done}}}}
```

But curl can handle the same response just fine...
```
# curl -i "http://ia-web/api/v0/swccd/build_automatch_query" -XPOST -d '{"opportunity_id": 3093}'
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
ETag: W/"86371c7746d599e12538d25a503f219a"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 4624fc82-bf1e-4799-9282-7352f5929555
X-Runtime: 0.066514
Transfer-Encoding: chunked

{"bool":{"must":{"term":{"_type":{"value":"Application"}}},"should":[{"bool":{"filter":[{"terms":{"opportunity_id":[3032]}},{"term":{"vam_effective_end_at":"20180306"}},{"term":{"vam_archive_at":"20180814"}},{"range":{"created_at":{"lt":"2018-03-07T07:59:59.999Z"}}},{"bool":{"minimum_should_match":1,"should":[{"bool":{"filter":[{"range":{"vam_form_field_30":{"gte":"2.8"}}},{"range":{"vam_form_field_271:submitted":{"gte":1}}},{"range":{"vam_form_field_33":{"gte":"12"}}},{"range":{"vam_form_field_34":{"gte":"9"}}},{"term":{"vam_form_field_224":"nursing - a.s."}},{"term":{"form_field_55":"yes"}}]}},{"bool":{"filter":[{"term":{"form_field_55":"yes"}},{"term":{"vam_form_field_397":"nursing - a.s."}},{"range":{"vam_form_field_33":{"gte":"12"}}},{"range":{"vam_form_field_271:submitted":{"gte":1}}},{"range":{"vam_form_field_30":{"gte":"2.8"}}},{"range":{"vam_form_field_34":{"gte":"9"}}}]}}]}}],"should":[],"must":[{"bool":{"filter":{"match_all":{}},"minimum_should_match":0,"should":[{"constant_score":{"filter":{"bool":{"filter":[{"range":{"form_field_30":{"gte":"2.8"}}},{"range":{"form_field_271:submitted":{"gte":1}}},{"range":{"form_field_33":{"gte":"12"}}},{"range":{"form_field_34":{"gte":"9"}}},{"term":{"form_field_224":"nursing - a.s."}},{"term":{"form_field_55":"yes"}}],"_name":"qg_1005"}}}},{"constant_score":{"filter":{"bool":{"filter":[{"term":{"form_field_55":"yes"}},{"term":{"form_field_397":"nursing - a.s."}},{"range":{"form_field_33":{"gte":"12"}}},{"range":{"form_field_271:submitted":{"gte":1}}},{"range":{"form_field_30":{"gte":"2.8"}}},{"range":{"form_field_34":{"gte":"9"}}}],"_name":"qg_1143"}}}}]}}],"must_not":[{"term":{"actualized_by":3093}},{"term":{"vam_category_state":"drafted"}}]}},{"bool":{"filter":[{"term":{"opportunity_id":3093}}],"must":[{"bool":{"filter":{"match_all":{}},"minimum_should_match":0,"should":[{"constant_score":{"filter":{"bool":{"filter":[{"range":{"form_field_30":{"gte":"2.8"}}},{"range":{"form_field_271:submitted":{"gte":1}}},{"range":{"form_field_33":{"gte":"12"}}},{"range":{"form_field_34":{"gte":"9"}}},{"term":{"form_field_224":"nursing - a.s."}},{"term":{"form_field_55":"yes"}}],"_name":"qg_1005"}}}},{"constant_score":{"filter":{"bool":{"filter":[{"term":{"form_field_55":"yes"}},{"term":{"form_field_397":"nursing - a.s."}},{"range":{"form_field_33":{"gte":"12"}}},{"range":{"form_field_271:submitted":{"gte":1}}},{"range":{"form_field_30":{"gte":"2.8"}}},{"range":{"form_field_34":{"gte":"9"}}}],"_name":"qg_1143"}}}}]}}],"should":[],"must_not":[]}}],"minimum_should_match":1}}
```

Not sure what to do. Thanks for the help.

**Comment by cjbottaro** [comment]
Forgot to mention...
```
# mix deps | egrep '(httpoison|hackney)'
* hackney 1.16.0 (Hex package) (rebar3)
  locked at 1.16.0 (hackney) 3bf0bebb
* httpoison 1.7.0 (Hex package) (mix)
  locked at 1.7.0 (httpoison) 975cc87c
```

**Comment by edgurgel** [comment]
Hey thanks for opening the issue! It seems to be related to https://github.com/benoitc/hackney/issues/638

I suggest going back to hackney 1.15.2 while this is fixed

**Comment by escobera** [comment]
@edgurgel is it possible to downgrade the dependency while hackney doesn't fix this issue?

**Comment by edgurgel** [comment]
@escobera One can override the hackney dependency on mix.exs using `override:true`

`{:hackney, "1.15.2", override: true}` should do the job

**Comment by bszaf** [comment]
@edgurgel The issue in `hackney` is fixed. Can this issue be closed as well?

**Comment by edgurgel** [comment]
Thanks, team!
